
const torneoData = {
    equipos: [
      { nombre: "Gallitos FC", escudo: "https://i.imgur.com/OwhPQsF.png", grupo: "A" },
      { nombre: "FC Caña 220V", escudo: "https://i.imgur.com/UP1TRuI.png", grupo: "A" },
      { nombre: "Manchester F7", escudo: "https://i.imgur.com/nvJ5B1c.png", grupo: "A" },
      { nombre: "Biloxi FC", escudo: "images/escudos/escudo.enc", grupo: "A" },
      { nombre: "Santos FC", escudo: "https://i.imgur.com/3xI12FY.png", grupo: "A" },
      { nombre: "Aguilas FC", escudo: "https://i.imgur.com/BPEeZDv.png", grupo: "B" },
      { nombre: "San Viernes FC", escudo: "https://i.imgur.com/AnmmwMh.png", grupo: "B" },
      { nombre: "Fuhrer FC", escudo: "https://i.imgur.com/epxf134.png", grupo: "B" },
      { nombre: "Legión Fútbol Club", escudo: "https://i.imgur.com/7zrhOBk.png", grupo: "B" },
      { nombre: "El graderío OG", escudo: "https://i.imgur.com/LwNiMjA.png", grupo: "B" },
      { nombre: "Juventus", escudo: "https://i.imgur.com/ACY7hS1.png", grupo: "B" },
      { nombre: "SD Argentina", escudo: "https://i.imgur.com/Fx6pK6T.png", grupo: "C" },
      { nombre: "Prófugos del gol", escudo: "https://i.imgur.com/QvupOW2.png", grupo: "C" },
      { nombre: "Barcelona FC", escudo: "https://i.imgur.com/1bk6hk5.png", grupo: "C" },
      { nombre: "1800 Hm", escudo: "https://i.imgur.com/iav8DU5.png", grupo: "C" },
      { nombre: "De aquí a las Bielas", escudo: "https://i.imgur.com/tgo3QAr.png", grupo: "C" },
      { nombre: "Brighton", escudo: "https://i.imgur.com/YRQE6xg.png", grupo: "C" },
      { nombre: "FC Rivers Plays", escudo: "https://i.imgur.com/wJ0BgVr.png", grupo: "C" },
      { nombre: "Tercera Opción", escudo: "https://i.imgur.com/nnfCwo3.png", grupo: "C" },
      { nombre: "Weest Juniors", escudo: "https://i.imgur.com/b7vefN9.png", grupo: "C" },
      { nombre: "Urban Soccer", escudo: "https://i.imgur.com/wE2qi1g.png", grupo: "C" },
      { nombre: "Sonido Master", escudo: "https://i.imgur.com/ZuSTdxn.png", grupo: "C" },
      { nombre: "Cerveza y Gol", escudo: "https://i.imgur.com/z4cvy26.png", grupo: "C" },
      { nombre: "Los descendientes FC", escudo: "https://i.imgur.com/KZUdOaD.png", grupo: "C" },
      { nombre: "Aston Biela FC", escudo: "https://i.imgur.com/eHFeLRk.png", grupo: "C" },
      { nombre: "Atlético DCL", escudo: "https://i.imgur.com/Sz92eIU.pngg", grupo: "C" },
      { nombre: "Varones FC", escudo: "https://i.imgur.com/es7QBoS.png", grupo: "C" },
      { nombre: "Dinasty FC", escudo: "https://i.imgur.com/C6RJYCP.png", grupo: "C" },
      { nombre: "6To Fima", escudo: "https://i.imgur.com/t504HLX.png", grupo: "C" },
      { nombre: "Huracán", escudo: "https://i.imgur.com/4fIieqW.png", grupo: "C" }
    ],
    grupos: {
      A: ["Gallitos FC", "FC Caña 220V", "Manchester F7", 
        "Biloxi FC", "Santos FC", "Aguilas FC", "San Viernes FC", "Fuhrer FC", 
        "Legión Fútbol Club", "El graderío OG"],
      B: ["Juventus", "SD Argentina", "Prófugos del gol", "Barcelona FC", "1800 Hm", 
        "De aquí a las Bielas", "Brighton", "FC Rivers Plays", "Tercera Opción", "Weest Juniors"],
      C: ["Urban Soccer", "Sonido Master", "Cerveza y Gol", "Los descendientes FC", "Aston Biela FC", 
        "Atlético DCL", "Varones FC", "Dinasty FC", "6To Fima", "Huracán"]
    },
  
    partidos: [
      { fecha: "2025-04-26", grupo: "A",equipo1: "Gallitos FC",equipo2: "Aguilas FC",resultado: "0-1"},       
      {fecha: "2025-04-25", grupo: "B",equipo1: "Brighton",equipo2: "Barcelona FC",resultado: "3-0"},
      {fecha: "2025-04-25", grupo: "C", equipo1: "Varones FC",equipo2: "Los descendientes FC",resultado: "9-0"},
      {fecha: "2025-04-25", grupo: "B", equipo1: "Juventus",equipo2: "De aquí a las Bielas",resultado: "0-4"},
      {fecha: "2025-04-25", grupo: "B", equipo1: "Prófugos del gol",equipo2: "1800 Hm",resultado: "2-0"},
      {fecha: "2025-04-26", grupo: "C", equipo1: "6To Fima",equipo2: "Sonido Master",resultado: "2-0"},
      {fecha: "2025-04-26", grupo: "B", equipo1: "Weest Juniors",equipo2: "Tercera Opción",resultado: "1-0"},
      {fecha: "2025-04-26", grupo: "C", equipo1: "Dinasty FC",equipo2: "Cerveza y Gol",resultado: "1-0"},
      {fecha: "2025-04-26",grupo: "A", equipo1: "Manchester F7",equipo2: "Santos FC",resultado: "0-7"},  
      {fecha: "2025-04-26",grupo: "A",equipo1: "Legión Fútbol Club",equipo2: "FC Caña 220V",resultado: "0-2"}, 
      {fecha: "2025-04-27",grupo: "B",equipo1: "Tercera Opción",equipo2: "SD Argentina",resultado: "1-0" },  
      {fecha: "2025-04-27", grupo: "A",equipo1: "El graderío OG",equipo2: "Fuhrer FC",resultado: "0-8"},  
      {fecha: "2025-04-27", grupo: "C",equipo1: "Urban Soccer", equipo2: "Atlético DCL",resultado: "9-0" },     
      { fecha: "2025-04-27", grupo: "C", equipo1: "Huracán",equipo2: "Dinasty FC",resultado: "4-0" }, 
      { fecha: "2025-04-27", grupo: "C", equipo1: "Cerveza y Gol", equipo2: "Aston Biela FC", resultado: "0-0" },
      { grupo: "C",  fecha: "2025-05-02", hora:"18:00",  equipo1: "Dinasty FC", equipo2: "Cerveza y Gol" },
      { grupo: "B", fecha: "2025-05-02", hora:"19:00", equipo1: "De aquí a las Bielas", equipo2: "Brighton" },
      { grupo: "B", fecha: "2025-05-02", hora:"20:00", equipo1: "1800 Hm", equipo2: "Juventus" },
      { grupo: "C", fecha: "2025-05-02", hora:"21:00", equipo1: "Aston Biela FC", equipo2: "Urban Soccer" },
      { grupo: "B", fecha: "2025-05-03", hora:"08:00", equipo1: "Barcelona FC", equipo2: "Tercera Opción" },
      { grupo: "B", fecha: "2025-05-03", hora:"09:00", equipo1: "SD Argentina", equipo2: "Weest Juniors" },
      { grupo: "B", fecha: "2025-05-03", hora:"10:00", equipo1: "FC Rivers Plays", equipo2: "Prófugos del gol" },
      { grupo: "A", fecha: "2025-05-03", hora:"11:00", equipo1: "Aguilas FC", equipo2: "San Viernes FC" },
      { grupo: "C", fecha: "2025-05-03", hora:"12:00", equipo1: "Sonido Master", equipo2: "Huracán" },
      { grupo: "C", fecha: "2025-05-03", hora:"13:00", equipo1: "Los descendientes FC", equipo2: "6To Fima" },
      { grupo: "A", fecha: "2025-05-04", hora:"08:00", equipo1: "Santos FC", equipo2: "Gallitos FC" },
      { grupo: "A", fecha: "2025-05-04", hora:"09:00", equipo1: "Biloxi FC", equipo2: "Legión Fútbol Club" },
      { grupo: "A", fecha: "2025-05-04", hora:"10:00", equipo1: "FC Caña 220V", equipo2: "El graderío OG" },
      { grupo: "A", fecha: "2025-05-04", hora:"11:00", equipo1: "Fuhrer FC", equipo2: "Manchester F7" },
      { grupo: "A", fecha: "2025-05-04", hora:"12:00", equipo1: "Atlético DCL", equipo2: "Varones FC" },
    ]
  };

